services:
  - type: web
    runtime: node
    name: paysat-backend
    plan: starter
    rootDir: .
    buildCommand: rm -rf src/node_modules && npm ci
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_PATH
        value: ./node_modules